name: Octokit CI

on:
   push:
     branches:
     - master
     - 4-stable
   pull_request:
     branches:
     - master
     - 4-stable

jobs:
  test:
    name: Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        ruby_version: [2.4.x, 2.5.x, 2.6.x]

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
         node-version: 12.x
    - name: Setup .netrc
      run: |
        chmod 600 spec/fixtures/.netrc
    - name: Install dependencies
      run: |
        gem install bundler
        gem update bundler
        bundle install --without development --jobs 4 --retry 3
    - name: Checkout fixtures-server
      uses: actions/checkout@v2
      with:
         repository: octokit/fixtures-server
         path: fixtures-server
    - name: Starting fixtures server
      run: |
         cd $GITHUB_WORKSPACE/fixtures-server
         npm ci
         node bin/server.js &
    - name: Test with RSpec
      env:
        GITHUB_CI: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        bundle exec rspec
